### ISSUE TITLE
More proof systems 

### ISSUE THREAD

**Issue by NikZak** [zkVerify/zkVerify#162]
Hey guys. Great idea and system. We need a groth16 proof on mnt curves verified. Can we add a verifier to your chain through abstract verifier interface?

**Comment by maromandarino** [comment]
Thanks for your interest in zkVerify! 

We're currently running our Phase 1 Incentivized Testnet, which includes rewards for implementing new verifiers like your Groth16 on MNT curves.

To start the process, please fill out the verifier submission form: https://forms.gle/idYKZ8n7T21embgLA

Our team will reach out to discuss further details.
Looking forward to having your verifier in our ecosystem!

**Comment by maromandarino** [comment]
@NikZak, also building a verifier will get you eligible for points in the zkVerify Incentivized Testnet Phase 1 - please have a look here: https://docs.zkverify.io/incentivizedtestnet/phases
